#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_webhook_repare_request:
    path: /api/webhook/repare-request
    controller: App\Controller\WebHookController::requestRepair
    method: [POST]