#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_chatbot_repare_request:
    path: /api/request
    controller: App\ChatBot\UI\RepairRequestController::acceptRepairRequest

api_chatbot_reply_to_message:
    path: /api/chat/message
    controller: App\ChatBot\UI\RepairRequestController::replyToMessage

api_chatbot_handshake:
    path: /api/chat/handshake
    controller: App\ChatBot\UI\RepairRequestController::handshake